port: 3300
database:
  mongo:
    url: sensitive
routing:
  base: "api"
globalExceptionFilter: true
jsonLimit: 2mb
middlewares:
  cors:
    activate: true
    origin:
      - "http://localhost"
      - "http://localhost:3000"
      - "http://localhost:3300"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowedHeaders:
      - "Content-Type"
      - "Authorization"
